# docker-compose.yml (pihole)
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"     # DNS
      - "53:53/udp"     # DNS
      - "8081:80/tcp"   # Web UI — kept off 80 so NPM can claim it later
    environment:
      TZ: "Europe/Warsaw"
      # FTL Engine Configs
      FTLCONF_webserver_api_password: "${PIHOLE_PASSWORD}"
      FTLCONF_dns_listeningMode: "ALL"  # required on default bridge network
      FTLCONF_dns_upstreams: "1.1.1.1;1.0.0.1"
      FTLCONF_misc_privacylevel: "3" # No logging
      # Custom domain DNS Wildcards
      FTLCONF_misc_dnsmasq_lines: |-
        address=/casamia-net.top/192.168.0.136
        address=/ts.casamia-net.top/${DOCKER_VM_TAILSCALE_IP}
    volumes:
      - /opt/docker-data/pihole:/etc/pihole
    cap_add:
      - NET_ADMIN   # needed even without using Pi-hole as DHCP server
      - SYS_TIME
      - SYS_NICE
    restart: unless-stopped