# docker-compose.yml (homepage)
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    env_file:
      - .env
    environment:
      HOMEPAGE_ALLOWED_HOSTS: "192.168.0.136:3001,debian-prox-docker:3001"
      PUID: 1000
      PGID: 1000
    ports:
      - "3001:3000"
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped