# docker-compose.yml (portainer)
services:
  portainer:
    image: portainer/portainer-ce:lts
    environment:
      - TRUSTED_ORIGINS=portainer.casamia-net.top,portainer.ts.casamia-net.top
    container_name: portainer
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/docker-data/portainer:/data
