# bookmarks.yaml
---
- Homelab:
    - GitHub Repo:
        - icon: github.png
          href: https://github.com/AlexSzczygielski/casa-mia-net-infrastructure
    - Tailscale Admin:
        - icon: tailscale.png
          href: https://login.tailscale.com/admin/machines